name: Convert AAB to APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download bundletool
        run: wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar -O bundletool.jar

      - name: Build Universal APK (unsigned)
        run: |
          java -jar bundletool.jar build-apks \
            --bundle=application-a7a38c51-3d15-43c4-99a5-7fe95097c33b.aab \
            --output=output.apks \
            --mode=universal \
            --overwrite

      - name: Extract APK
        run: unzip -o output.apks 'universal.apk'

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: universal.apk
